Test/Test/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('todoList/', include("todoList.urls"))
]

Test/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("shini", views.shini, name="shini"),
    path("<str:name>", views.greet, name="greet")
]

Test/newyear/urls.py
from django.urls import path

from . import views

app_name = "newyear"

urlpatterns = [
    path("", views.index, name="index")
]

Test/todoList/urls.py
from django.urls import path

from . import views

app_name = "todoList"

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

Test/todoList/models.py
from django.db import models

# Create your models here.

Test/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def shini(request):
    return HttpResponse("Hello Shini")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name":name.capitalize()
    })

Test/newyear/views.py
from django.shortcuts import render

import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

Test/todoList/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

tasks = ["Do Hw", "Dance"]

# Create your views here.
class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "todoList/index.html", {
        "tasks":request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("todoList:index"))
        else:
            return render(request, "todoList/add.html", {
                "form": form
            })
    return render(request, "todoList/add.html", {
        "form":NewTaskForm()
    })

Test/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Hello</title>
</head>

<body>
    <h1>Hello, {{ name }}</h1>
</body>

</html>

Test/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Hello</title>
</head>

<body>
    <h1>Hello, World!</h1>
</body>

</html>

Test/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE>
<html lang="en">

<head>
    <title>Is it new year?</title>

    <link rel="stylesheet" href="{% static 'newyear/style.css' %}">
</head>

<body>
    {% if newyear %}
    <h1>YES</h1>
    {% else %}
    <h1>NO</h1>
    {% endif %}
</body>

</html>

Test/todoList/templates/todoList/add.html
{% extends "todoList/layout.html" %}

{% block body %}

<h1>Add:</h1>
<form action="{% url 'todoList:add' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>

<a href="{% url 'todoList:index' %}">Yours Tasks</a>

{% endblock %}

Test/todoList/templates/todoList/index.html
{% extends "todoList/layout.html" %}

{% block body %}
<h1>ToDo:</h1>
<ul>
    {% for task in tasks %}
        <li>{{ task }}</li>
    {% empty %}
        <li>No Tasks</li>

    {% endfor %}
</ul>

<a href="{% url 'todoList:add' %}">Add Tasks</a>
{% endblock %}

Test/todoList/templates/todoList/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>ToDo</title>
    <link rel="stylesheet" href="{% static 'todoList/style.css' %}">
</head>

<body>

</body>
    {% block body %}
    {% endblock %}
</html>